AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FinOps+ Agent Backend — FastAPI on AWS Lambda + HTTP API (reuse existing DynamoDB table)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 1024
    Architectures: [x86_64]
    Environment:
      Variables:
        SQLITE_URL: sqlite:////tmp/finops.db
        # ---- App configuration ----
        PROVIDER: bedrock
        BEDROCK_REGION: us-east-1
        BEDROCK_MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0

        # ---- Data sources ----
        S3_BUCKET: !Ref S3DataBucket
        S3_KEY: billing_data.csv
        S3_UPLOAD_PREFIX: uploads/

        # ---- Auth (optional) ----
        COGNITO_ENABLED: 'true'
        COGNITO_REGION: us-east-2
        COGNITO_USER_POOL_ID: us-east-2_3hGBifjKi
        COGNITO_AUDIENCE: 5sop8nmqobu3fflaqres1ckvgq

        # ---- Rate limiting (optional) ----
        RATE_LIMIT_ENABLED: 'true'
        RATE_LIMIT_WINDOW_SEC: '60'
        RATE_LIMIT_MAX_REQUESTS: '15'

        # ---- DDB (reused) ----
        DDB_TABLE: !Ref ExistingActionsTableName
        DDB_REGION: us-east-1

        # ---- PDF branding ----
        PDF_BRAND: "FinOps+ Agent"
        PDF_LOGO_PATH: "./static/logo.png"
        PDF_TAGLINE: "AWS + Kiros | Hackathon Prototype"

        # ---- SQLAlchemy on Lambda /tmp ----
        SQLALCHEMY_URL: sqlite:////tmp/sqlite/finops.db

        # ---- FastAPI CORS middleware origin ----
        FRONTEND_ORIGIN: https://d2gc5d8166vwh1.cloudfront.net

Parameters:
  S3DataBucket:
    Type: String
    Default: finops-demo-bucket3905
    Description: S3 bucket that stores CSVs and uploads

  ExistingActionsTableName:
    Type: String
    Default: FinOpsActions
    Description: Use an existing DynamoDB table (stack will NOT create one)

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - https://d2gc5d8166vwh1.cloudfront.net
          - http://localhost:5173
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"
        ExposeHeaders:
          - content-disposition
          - content-type
        AllowCredentials: true
        MaxAge: 600
      FailOnWarnings: false

  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: lambda_handler.handler
      Runtime: python3.12
      Events:
        ProxyAny:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
            ApiId: !Ref HttpApi
        # (optional but handy) ensure root path '/' also routes
        ProxyRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
            ApiId: !Ref HttpApi
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            Effect: Allow
            Action:
              - bedrock:InvokeModel
              - bedrock:InvokeModelWithResponseStream
            Resource: "*"
        - Statement:
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject         # <-- add
              - s3:DeleteObject      # <-- add
            Resource:
              - !Sub "arn:aws:s3:::${S3DataBucket}"
              - !Sub "arn:aws:s3:::${S3DataBucket}/*"
        - Statement:
            Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:GetItem
              - dynamodb:UpdateItem
              - dynamodb:Query
              - dynamodb:Scan
            Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ExistingActionsTableName}"

Outputs:
  ApiUrl:
    Description: Public API base URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/"

  FunctionName:
    Description: Deployed Lambda function name
    Value: !Ref ApiFunction

  TableUsed:
    Description: DynamoDB table this stack uses
    Value: !Ref ExistingActionsTableName
